CREATE TABLE years(
	YearID SMALLINT(4) UNSIGNED NOT NULL,
	Active BOOLEAN DEFAULT FALSE,
	Winners MEDIUMINT(7),
	Losers MEDIUMINT(7),
	PRIMARY KEY(YearID)
)

CREATE TABLE guilds(
	GuildID BIGINT(19) UNSIGNED NOT NULL,
	WhitelistEnabled BOOLEAN DEFAULT FALSE,
    WhitelistedChannels VARCHAR(210) DEFAULT '[]',
    PRIMARY KEY(GuildID)
);

CREATE TABLE users(
	UserID BIGINT(19) UNSIGNED NOT NULL,
	TimeZone FLOAT(3),
    PRIMARY KEY(UserID)
);

CREATE TABLE attempts(
	AttemptID MEDIUMINT(7) UNSIGNED NOT NULL AUTO_INCREMENT,
	YearID SMALLINT(4) UNSIGNED NOT NULL,
	Lost BOOLEAN DEFAULT FALSE,
	LossDate DATE,
	LossReason VARCHAR(256),
	UserID BIGINT(19) UNSIGNED NOT NULL,
    PRIMARY KEY(AttemptID)
);


ALTER TABLE attempts
ADD FOREIGN KEY(UserID) REFERENCES users(UserID);

ALTER TABLE attempts
ADD FOREIGN KEY(YearID) REFERENCES years(YearID);