CREATE TABLE years(
	YearID SMALLINT(4) NOT NULL,
	Active BOOLEAN DEFAULT FALSE,
	Winners SMALLINT(6),
	Losers SMALLING(6),
	PRIMARY KEY(YearID)
)

CREATE TABLE guilds(
	GuildID BIGINT(19) NOT NULL,
	WhitelistEnabled BOOLEAN DEFAULT FALSE,
    WhitelistedChannels VARCHAR(210),
    PRIMARY KEY(GuildID)
);

CREATE TABLE users(
	UserID BIGINT(19) NOT NULL,
	TimeZone FLOAT(3),
    PRIMARY KEY(UserID)
);

CREATE TABLE attempts(
	AttemptID BIGINT(19) NOT NULL AUTO_INCREMENT,
	Year SMALLINT(4) NOT NULL,
	Lost BOOLEAN DEFAULT FALSE,
	LossDate DATE,
	LossReason VARCHAR(256),
	UserID BIGINT(19),
    PRIMARY KEY(AttemptID)
);


ALTER TABLE attempts
ADD FOREIGN KEY(UserID) REFERENCES users(UserID);